config/routes.rb
Rails.application.routes.draw do
  resources :sensors
   devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:show]
  get 'users/:id/change_admin' => 'users#change_admin'
  get 'users/:id/permission' => 'users#permission', as: :user_permission
  resources :families
  get '/devices/turn_on' => 'devices#turn_on'
  get '/devices/turn_off' => 'devices#turn_off'
  get '/devices/turn_on_all' => 'devices#turn_on_all'
  get '/devices/turn_off_all' => 'devices#turn_off_all'
  get '/devices/state_change' => 'devices#state_change'
  resources :devices
  get '/remote' => 'remote#index'

  root 'devices#index'
  
  get 'pages/about'

  get 'pages/contact'

  get 'pages/welcome'

end

app/models/device.rb
class Device < ActiveRecord::Base
	validates :name, presence: true
	belongs_to :user
	belongs_to :family
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
before_action :set_device, only: [:state_change, :show, :destroy]
before_action :check_user
before_action :check_admin, only: [:new, :create, :destroy]

	def index
		@devices = current_user.family.devices.order("id asc").all
		if !@devices.nil? && !current_user.admin?
			array = Array.new
			for device in @devices
				device.user_id = device.user_id.split(',')
				if device.user_id.include?(current_user.id.to_s)
					array.push device
				end
			end
			@devices = array.sort_by {|a| a.id}
		end
	end		

	def state_change
		# raise @device.inspect
		if @device.state
			@device.update(state: 0)
		else
			@device.update(state: 1)
		end
		redirect_to devices_path
	end

	def new
		@device = current_user.devices.new
	end

	def set_device
		@device = current_user.family.devices.find(params[:id])
	end

	def show
	end

	def create
		@device = current_user.devices.new(device_params)
		@device.family_id = current_user.family_id
		respond_to do |format|
			if @device.save
				format.html { redirect_to @device, notice: 'Device was successfully added.' }
        		format.json { render :show, status: :created, location: @device }
			else
        		format.html { render :new }
       		    format.json { render json: @device.errors, status: :unprocessable_entity }
      		end
      	end
    end

    def destroy
    	@device.destroy
    	respond_to do |format|
          format.html { redirect_to devices_path, notice: 'Device was successfully removed.' }
    	  format.json { head :no_content }
  	 	end
    end

    def turn_on
		@device = Device.find(params[:id])
		@device.update(state: 1)
		respond_to do |format|
			format.js{ render :action => "index" }
		end
	end

	def turn_on_all
		@devices = current_user.family.devices.order("id asc").all
		if !@devices.nil? && !current_user.admin?
			array = Array.new
			for device in @devices
				device.user_id = device.user_id.split(',')
				if device.user_id.include?(current_user.id.to_s)
					array.push device
				end
			end
			@devices = array.sort_by {|a| a.id}
		end
		for device in @devices
			device.update(state: 1)
		end
		respond_to do |format|
			format.js{ render :action => "index" }
		end
	end

	def turn_off
		@device = Device.find(params[:id])
		@device.update(state: 0)
		respond_to do |format|
			format.js{ render :action => "index" }
		end
	end

	def turn_off_all
		@devices = current_user.family.devices.order("id asc").all
		if !@devices.nil? && !current_user.admin?
			array = Array.new
			for device in @devices
				device.user_id = device.user_id.split(',')
				if device.user_id.include?(current_user.id.to_s)
					array.push device
				end
			end
			@devices = array.sort_by {|a| a.id}
		end
		for device in @devices
			device.update(state: 0)
		end
		respond_to do |format|
			format.js{ render :action => "index" }
		end
	end

	def device_params
      params.require(:device).permit(:name, :state, :rpi_id, :family_id)
    end

    def check_user
    	unless user_signed_in?
    		redirect_to url_for(action: 'welcome', controller: 'pages')
    	end
    end

    def check_admin
    	unless current_user.admin?
    		redirect_to devices_path, alert: "Only admins can do that."
    	end
    end		
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_devices.html.erb
<% @devices = current_user.family.devices.order("id asc").all
		if !@devices.nil? && !current_user.admin?
			array = Array.new
			for device in @devices
				device.user_id = device.user_id.split(',')
				if device.user_id.include?(current_user.id.to_s)
					array.push device
				end
			end
			@devices = array.sort_by {|a| a.id}
		end %>
<% if @devices.present? %>
<table class="table table-hover table-condensed">
	<tr>
		<th>#</th>
		<th>Device name</th>
		<th>State</th>
		<th>Control</th>
	</tr>
	<% count = 0 %>
<% for device in @devices %>
<tr>
	<td><%= count+=1 %></td>
	<td><%= link_to device.name, device %></td>
	<!-- <td><%= device.state %></td> -->
	<% if device.state %>
	<td> On </td>
	<% else %>
	<td> Off </td>
	<%end%>
	<% if device.state %>
	<td><%= link_to 'Turn off<span class="spinner"><i class="fa fa-refresh"></i></span>'.html_safe(), {:controller => 'devices',:action => 'state_change',:id => device.id}, remote: true, class: "btn btn-danger has-spinner" %></td>
	<% else %>
	<td><%= link_to 'Turn on<span class="spinner"><i class="fa fa-refresh"></i></span>'.html_safe(),{ :controller => 'devices', :action => 'state_change',:id => device.id}, :remote => true, class: "btn btn-primary has-spinner" %></td>
	<% end %>
</tr>
<% end %>
<% else %>
No devices added yet!
<% end %>
<script type="text/javascript">
$(function(){
    $('.has-spinner').click(function() {
        $(this).toggleClass('active');
        $(this).toggleClass('disabled');
    });
});
</script>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
     <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@device.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/devices/index.html.erb
<h1 class="page-header">Dashboard</h1>

<h2> Your devices </h2>
<% if user_signed_in? && current_user.admin?%>
<%= link_to "Add a device", new_device_path, class: "btn btn-primary" %>
<% end %>
<br><br>
<div class="ajax"><%= render 'devices' %></div>

app/views/devices/index.js.erb
$('.ajax').html('<%= j render("devices") %>')

app/views/devices/new.html.erb
<h1 class="page-header">New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path , class: "btn btn-link" %>

app/views/devices/show.html.erb
<h1 class="page-header"><%= @device.name %></h1>

<%= link_to "Back" , devices_path ,class: "btn btn-link"%>
<% if current_user.admin? %>
<%= link_to "Remove", @device , method: :delete,class: "btn btn-link" %>
<% end %>