config/routes.rb
Rails.application.routes.draw do
  resources :sensors
   devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:show]
  get 'users/:id/change_admin' => 'users#change_admin'
  get 'users/:id/permission' => 'users#permission', as: :user_permission
  resources :families
  get '/devices/turn_on' => 'devices#turn_on'
  get '/devices/turn_off' => 'devices#turn_off'
  get '/devices/turn_on_all' => 'devices#turn_on_all'
  get '/devices/turn_off_all' => 'devices#turn_off_all'
  get '/devices/state_change' => 'devices#state_change'
  resources :devices
  get '/remote' => 'remote#index'

  root 'devices#index'
  
  get 'pages/about'

  get 'pages/contact'

  get 'pages/welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :devices, dependent: :destroy
  belongs_to :family
  validates :first_name, :last_name , presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
prepend_before_filter :require_no_authentication, only: [ :cancel]
before_filter :authenticate_user!
before_filter :is_admin?, only: [:new]
  # GET /resource/sign_up
  def new
    if params[:family_id]
      @family_id = params[:family_id]
      @first_user = true
    end
    if @family_id
      @family = Family.find(@family_id)
    end
    @user = User.new
    set_minimum_password_length
  end

  # POST /resource
  def create
    @family_id = params[:user][:family_id]
    @family = Family.find(@family_id)
    p = params[:user][:admin]
    # raise p.inspect
    if p
      @first_user = true
    end
    @user = User.new(first_name: params[:user][:first_name], last_name: params[:user][:last_name],email: params[:user][:email], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation], family_id: params[:user][:family_id], admin: params[:user][:admin])
    if @user.save
      if @user.active_for_authentication?
        unless current_user.present?
          set_flash_message :notice, :signed_up if is_navigational_format?
          sign_up(:user, @user)
        else
          set_flash_message :notice, :user_signed_up
        end
        respond_with @user, :location => after_sign_up_path_for(@user)
      else
        set_flash_message :notice, :"signed_up_but_#{@user.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with @user, :location => after_inactive_sign_up_path_for(@user)
      end
    else
      clean_up_passwords @user
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :family_id
    devise_parameter_sanitizer.for(:sign_up) << :admin
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    if current_user.admin?
      user_path(current_user)
    else
      root_url
    end
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def is_admin?
  unless params[:family_id]  
    if user_signed_in? # if user signed
    if current_user.admin? # if adminstrator return true
       true
    else
       flash[:error] = "Only admins can create new users!" 
       redirect_to root_url
    end
    else
      flash[:error] = "You need to sign in before continuing." 
      redirect_to new_user_session_path
    end

    end
  else
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
	@user = User.find(params[:id])
	@family = current_user.family
	@users = @family.users.all
	@devices = @user.devices.all
end

def permission
	@user = User.find(params[:id])
	@device = Device.find(params[:device])
	array = @device.user_id.split(',')
	unless array.include?(@user.id.to_s)
		array.push @user.id
		
		array.compact!
	    array=array.join(',')
	    @device.update(user_id: array)
	    respond_to do |format|
	    	format.html{redirect_to @user, notice: "Permissions updated!"}
	    end
	else
		respond_to do |format|
	    	format.html{redirect_to @user, notice: "User already has permission."}
	    end
	end

end

def change_admin
	@user = User.find(params[:id])
	if @user.admin?
		@user.update(admin: false)
	else
		@user.update(admin: true)
	end
	redirect_to user_path
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h1 class="page-header">
<% if current_user == @user %>
	Hello <%= current_user.first_name+' !' %>
<% else %>
<%= @user.first_name+' '+@user.last_name %>
<% end %></h1>
<% if current_user.admin? %>
<%= link_to "Add New User",new_user_registration_path, class: "btn btn-primary" %>
<% if @user != current_user %>
<% if @user.admin? %>
<%= link_to "Remove as Admin", url_for(action: 'change_admin', id: @user.id), data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
<% else %> 
<%= link_to "Add as Admin",url_for(action: 'change_admin', id: @user.id), data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
<% end %>
<% end %>
<% end %>
<!--
We will create a family tree using just CSS(3)
The markup will be simple nested lists
-->
<div class="tree">
	<ul>
		<li>
			<%= link_to @family.name, family_path %>
			<ul>
				<% for user in @users %>
				<li><% if user.== current_user %>
					<%= link_to 'You', user %>
					<% else %>
					<%= link_to user.first_name, user %>
					<% end %>
					<ul>
						<% @devices = user.family.devices.all %>
						<% for device in @devices %>
						<% device.user_id = device.user_id.split(',') %>
						<% if device.user_id.include?(user.id.to_s) || user.admin?%>
						<li>
							<%= link_to device.name, device %>
						</li>
						<% end %>
						<% end %>
					</ul>
				</li>
				<% end %>
			</ul>
		</li>
	</ul>
</div>
<% @devices = @user.family.devices.order("id asc").all %>
<h2>Permissions</h2>

<table class="table table-hover table-condensed">
	<tr>
		<th>#</th>
		<th>Device name</th>
		<th>State</th>
		<th>Permission</th>
		<% if current_user.admin? %>
		<th></th>
		<% end %>
	</tr>
	<% count = 0 %>
<% for device in @devices %>
<tr><% device.user_id = device.user_id.split(',') %>
	<td><%= count+=1 %></td>
	<td><%= device.name %></td>
	<td><% if device.state %>
	On
	<% else %>
	Off
	<%end%></td>
	<td><% if device.user_id.include?(@user.id.to_s) || @user.admin? %>
		Yes
		<% else %>
		No
		<% end %>
	</td>
	<% if current_user.admin? && !@user.admin?%>
	<% if device.user_id.include?(@user.id.to_s) || @user.admin? %>
		<td><%= link_to "Remove Permission",{:controller => "users",action: 'permission', id: @user.id, device: device.id},class: "btn btn-danger btn-block" %></td>
		<% else %>
		<td><%= link_to "Add Permission",{:controller => "users",action: 'permission', id: @user.id, device: device.id},class: "btn btn-primary btn-block" %></td>
		<% end %>
		<% else %>
		<td></td>
	<% end %>
</tr>
<% end %>
</table>