config/routes.rb
Rails.application.routes.draw do
  resources :sensors
   devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  resources :users, only: [:show]
  get 'users/:id/change_admin' => 'users#change_admin'
  get 'users/:id/permission' => 'users#permission', as: :user_permission
  resources :families
  get '/devices/turn_on' => 'devices#turn_on'
  get '/devices/turn_off' => 'devices#turn_off'
  get '/devices/turn_on_all' => 'devices#turn_on_all'
  get '/devices/turn_off_all' => 'devices#turn_off_all'
  get '/devices/state_change' => 'devices#state_change'
  resources :devices
  get '/remote' => 'remote#index'

  root 'devices#index'
  
  get 'pages/about'

  get 'pages/contact'

  get 'pages/welcome'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Smart Home",root_path , class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About",pages_about_path %></li>
        <li><%= link_to "Contact",pages_contact_path %></li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to current_user.first_name.titleize+' '+current_user.last_name.titleize, current_user %></li>
              <li><%= link_to "Log out", destroy_user_session_path , method: :delete %></li>
        <% else %> 
            <li><%= link_to "Log in", new_user_session_path , method: :get %></li>
          <li><%= link_to "Get Started", new_family_path %></li>
          <% end %>
        </ul>
	</div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
<ul class="nav nav-sidebar">
<li class="<%= 'active' if params[:controller] == 'devices' %>"><%= link_to "Switches", devices_path %></li>
<li class="<%= 'active' if params[:controller] == 'sensors' %>"><%= link_to "Sensors", sensors_path %></li>
<li class="<%= 'active' if params[:controller] == 'remote' %>"><%= link_to "Remote", remote_path %></li>
</ul>
</div>

app/views/layouts/_speech.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Voice command</h4>
      </div>
      <div class="modal-body">
<h2>Transcription</h2>
<textarea id="transcription" readonly="readonly"></textarea>
<span class="hidden">
    <span>Results:</span>
    <label><input type="radio" name="recognition-type" value="final" checked="checked" /> Final only</label>
    <label><input type="radio" name="recognition-type" value="interim" /> Interim</label>
</span>
<h3>Simon Says</h3>
<div id="log"></div>
<div class="buttons-wrapper">
  <button id="button-play-ws" class="button-demo"><%= fa_icon "microphone", style: "font-size: 25px;" %></button>
</div>
<span id="ws-unsupported" class="hidden">API not supported</span>
</div>
      
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Smart Home</title>
  <%= Gon::Base.render_data %>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/navbar' %>
<% if user_signed_in? %>
<div id="mic" data-target="#myModal" data-toggle="modal"><%= fa_icon "microphone", style: "font-size: 25px;"%></div>
<%= render 'layouts/speech' %>
<% end %>

	<%if params[:controller] == 'pages' && params[:action] != 'welcome'%>
<div class="container-fluid">
	<div class= "row1">
	<% flash.each do |name, msg| %>
			<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name == "notice" ? "success" : "danger"%> alert-dismissble">
					<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"> Close</span></button>
					<%= content_tag :div,msg, :id=> "flash_#{name}" %>
				</div>
			<% end %>
      <% end %>
      <%= yield %>
    </div>
  </div>
      <% elsif params[:controller] == 'pages' && params[:action] == 'welcome' %>
      <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger"%> alert-dismissble" style="position:absolute;width:100%;">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"> Close</span></button>
          <%= content_tag :div,msg, :id=> "flash_#{name}" %>
        </div>
      <% end %>
			<% end %>
	<%= yield %>
	<% else %>
  <div class="container-fluid">
	<div class="row">
		<%= render 'layouts/sidebar' %>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<% flash.each do |name, msg| %>
			<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name == "notice" ? "success" : "danger"%> alert-dismissble">
					<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only"> Close</span></button>
					<%= content_tag :div,msg, :id=> "flash_#{name}" %>
				</div>
			<% end %>
		<% end %>
		<%= yield %>
	</div>
	</div>
</div>
	<% end %>

<script type="text/javascript">
if(gon.logged_in){
  var i,dev=new Array(),sen=new Array(),temp,humid;
  gon.watch('devices',{interval: 3000},function(devices){
    dev=[];
    for(i=0;i<devices.length;i++){
      var d = {id:devices[i].id,name:devices[i].name,state:devices[i].state};
      dev.push(d);
    }
  });
  gon.watch('sensors',{interval: 3000},function(sensors){
    sen=[];
    for(i=0;i<sensors.length;i++){
      var val = Math.round(sensors[i].value);
      if(sensors[i].name.toLowerCase() == "temperature"){
        temp = val;
      }
      else if(sensors[i].name.toLowerCase() == "humidity"){
        humid = val;
      }
      var s = {id:sensors[i].id,name:sensors[i].name,value:val};
      sen.push(s);
    }
  });
   var accessToken = "66b0de1a2ecd46afb4f25abcb9cc278c",
      subscriptionKey = "82cb8764-2927-45c5-8043-a614e9cd8a19",
      baseUrl = "https://api.api.ai/v1/",
      $speechInput,
      $recBtn,
      recognition,
      messageCouldntHear = "I couldn't hear you, could you say that again?",
      messageInternalError = "Oh no, there has been an internal server error",
      messageSorry = "I'm sorry, I don't have the answer to that yet.";
// Test browser support
window.SpeechRecognition = window.SpeechRecognition  ||
                              window.webkitSpeechRecognition ||
                                 null;
var results = [];
if (window.SpeechRecognition === null) {
  document.getElementById('ws-unsupported').classList.remove('hidden');
  var div = document.getElementById('button-play-ws');
  div.innerHTML = '<%= fa_icon "microphone-slash", style: "font-size: 25px;" %>';
  var div2 = document.getElementById('mic');
  div2.innerHTML = '<%= fa_icon "microphone-slash", style: "font-size: 25px;" %>';
  div2.className += "disabled";
  document.getElementById('button-play-ws').setAttribute('disabled', 'disabled');
  document.getElementById('button-stop-ws').setAttribute('disabled', 'disabled');
} 
else {  
  var recognizer = new window.SpeechRecognition();
  var transcription = document.getElementById('transcription');
  var log = document.getElementById('log');
  // Recogniser doesn't stop listening even if the user pauses
  // recognizer.continuous = true;
  // Start recognising
  recognizer.onresult = function(event) {
    transcription.textContent = '';
    log.innerHTML = '';
    results.push(event.results);
    results.reverse();
    results.forEach(function(val,i){
      var el = val[0][0].transcript.toLowerCase();
      transcription.textContent = el;
      $.ajax({
        type: "POST",
        url: baseUrl + "query/",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        headers: {
          "Authorization": "Bearer " + accessToken,
          "ocp-apim-subscription-key": subscriptionKey
        },
        data: JSON.stringify({q: el, lang: "en"}),
        success: function(data) {
          prepareResponse(data);
        },
        error: function() {
          log.innerHTML = messageInternalError;
        }
      });
    });
    results = [];
  };
  function prepareResponse(val) {
      var debugJSON = JSON.stringify(val, undefined, 2),
        spokenResponse = val.result.speech,i,match=0;
        if (spokenResponse == ""){
          spokenResponse = val.result.metadata.html;
        }
        else{
          if(val.result.parameters.device){
            for(i=0;i<dev.length;i++) {
              if(dev[i].name.toLowerCase().search(val.result.parameters.device)!= -1){
                var id = dev[i].id;
                match++;
                if(val.result.action == "turnon"){
                  if(dev[i].state){
                    log.innerHTML = "The device is already on.";
                  }
                  else{
                    $.get("/devices/turn_on",{"id":id});
                    log.innerHTML = spokenResponse;  
                  }
                }
                else if(val.result.action == "turnoff"){
                  if(dev[i].state){
                    $.get("/devices/turn_off",{"id":id});
                    log.innerHTML = spokenResponse;
                  }
                  else{
                     log.innerHTML = "The device is already off.";
                  }
                }
              }
            }
            if(val.result.parameters.device == "all devices"){
                match++;
                if(val.result.action == "turnon"){
                  $.get("/devices/turn_on_all");
                  log.innerHTML = spokenResponse;
                }
                else if(val.result.action == "turnoff"){
                  $.get("/devices/turn_off_all");
                  log.innerHTML = spokenResponse;
                }
              }
            if(match==0){
              log.innerHTML = "Sorry but either you haven't added that device or you don't have permission to use it."
            }
          }
          else if(val.result.action == "checksensor"){
           for(i=0;i<sen.length;i++) {
                if(val.result.parameters.sensor == "temperature" && sen[i].name.toLowerCase() == "temperature"){
                  log.innerHTML = "The current room temperature is "+sen[i].value+"&deg;C";
                  match++;
                }
                else if(val.result.parameters.sensor == "humidity" && sen[i].name.toLowerCase() == "humidity"){
                  log.innerHTML = "The current humidity is "+sen[i].value+"%";
                  match++;
                }
                else if(val.result.parameters.sensor == "lpg" && sen[i].name.toLowerCase() == "lpg gas sensor"){
                  if(sen[i].value == 0){
                    log.innerHTML = "Currently the sensor is not detecting any leak";  
                  }
                  else{
                    log.innerHTML = "Alert! LPG gas leak detected.";  
                  }
                  match++;
                }
                else if(val.result.parameters.sensor == "co2" && sen[i].name.toLowerCase() == "co2 gas sensor"){
                  if(sen[i].value == 0){
                    log.innerHTML = "Currently the sensor is not detecting any leak";  
                  }
                  else{
                    log.innerHTML = "Alert! Something is burning in the house.";  
                  }
                  match++;
                }
            }
            if(val.result.parameters.sensor == "weather"){
                log.innerHTML = "The current room temperature is "+temp+"&deg;C and humidity is "+humid+'%';
                match++;
              }
            if(match==0){
              log.innerHTML = "Sorry but you haven't added that sensor."
            }
          }
        }
        if(log.innerHTML == ''){
          if(val.result.action){
            if(val.result.action.search("smalltalk") != -1 || val.result.action.search("name") != -1 || val.result.action.search("calculator") != -1 || val.result.action.search("wisdom") != -1){
              log.innerHTML = spokenResponse;    
            }
          }
          else{
            log.innerHTML = messageSorry;
          }
        }
      console.log(debugJSON);
      document.getElementById('button-play-ws').style.color = "black";
    }

  // Listen for errors
  recognizer.onerror = function(event) {
    //log.innerHTML = 'Recognition error: ' + event.message + '<br />' + log.innerHTML;
    transcription.textContent = '';
    log.innerHTML = messageCouldntHear;
    document.getElementById('button-play-ws').style.color = "black";
  };
  var play = document.getElementById('button-play-ws');
  play.addEventListener('click', function() {play.style.color = "red";
    // Set if we need interim results
    recognizer.interimResults = document.querySelector('input[name="recognition-type"][value="interim"]').checked;
    recognizer.stop();
    try {
      transcription.textContent = 'Listening...';
      log.textContent = 'What can I do for you?';
      recognizer.start();
    } catch(ex) {
      log.innerHTML = messageCouldntHear;
      transcription.textContent = '';
      play.style.color = "black";
    }
  });
  document.getElementById('mic').addEventListener('click', function() {
      document.getElementById('button-play-ws').style.color="red";
      try {
      transcription.textContent = 'Listening...';
      log.textContent = 'What can I do for you?';
      recognizer.start();
    } catch(ex) {
      log.innerHTML = messageCouldntHear;
      transcription.textContent = '';
      document.getElementById('button-play-ws').style.color="black";
    }
  });
}
}
</script>
</body>
</html>